name: Upload Website

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.17'

    - name: Build wasm file
      run: GOARCH=wasm GOOS=js go build -o build/web/app.wasm ./app

    - name: Build app file
      run: go build -o build/app ./app

    - name: Generate Website
      run: cd build && export PRODUCTS_KEY=${{ secrets.PRODUCTS_KEY }} && ./app && rm ./app

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Remove html extensions
      run: find -type f -name '*.html' | while read f; do mv "$f" "${f%.html}"; done

    - name: Deploy content to S3 bucket
      run: aws s3 cp ./build/web s3://kreativroni.de && aws s3 cp ./build/*.js s3://kreativroni.de && aws s3 cp ./build/app.css s3://kreativroni.de && aws s3 cp ./build/manifest.webmanifest s3://kreativroni.de

    - name: Deploy sites to S3 bucket
      run: |
        aws s3 cp ./build/index s3://kreativroni.de --content-type "text/html" \
        aws s3 cp ./build/shop s3://kreativroni.de --content-type "text/html" \
        aws s3 cp ./build/fashion s3://kreativroni.de --content-type "text/html" \
        aws s3 cp ./build/about_me s3://kreativroni.de --content-type "text/html" \
        aws s3 cp ./build/legal_notice s3://kreativroni.de --content-type "text/html"